movie:
  max_name: 100
  min_length: 20
  max_length: 600
  max_desc: 5000
  languages:
    - :en
    - :vi
    - :kr
    - :jp
    - :ru
    - :cn
  status:
    - :pending
    - :airing
    - :archived
  rates:
    - :G
    - :PG
    - :PG-13
    - :R
    - :NC-17
  movie_index: 6
  movie_sidebar: 3

genre:
  max_name: 20

theater:
  max_name: 100
  max_desc: 5000

screen:
  max_name: 80
  max_desc: 5000
  min_seat: 5
  max_seat: 50

user:
  max_first: 50
  max_last: 100
  genders:
    - :male
    - :female
    - :other
  roles:
    - :user
    - :admin

order:
  status:
    - pending
    - reserved
    - cancelled
    - succeeded
    - failed

date_format: "%A, %e/%m/%Y"
time_format: "%H:%M"
